---
- hosts: localhost
  tasks:
  - name: Ensure /nwserver dir
    file:
      path: /nwserver
      state: directory
      owner: nwserver-user
      group: nwserver-group
      mode: 0750

  - name: Download NWNEE Zip
    get_url:
      url: https://nwn.beamdog.net/downloads/nwnee-dedicated-8193.34.zip
      dest: ~/

  - name: Unzip NWNEE Zip
    unarchive:
      src: ~/nwnee-dedicated-8193.34.zip
      dest: /nwserver/

  - name: Set nwserver-linux exec
    file:
      path: /nwserver/bin/linux-x86/nwserver-linux
      mode: a+x
      owner: nwserver-user
      group: nwserver-group
