name: BOTDR Module Release

on:
  push:
    tags:
      - "v*"

permissions:
    id-token: write
    contents: read


env:
    python_version: "3.12"

jobs:
  dev-release:
    runs-on: ubuntu-latest
    if: startsWith (github.ref, 'refs/tags/v') && contains(github.ref, '-beta')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
      - name: Setup OIDC AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
            role-session-name: GitHubActions-botdr-${{ github.sha }}
            aws-region: us-east-1